name: Reviewdog Linting

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Linter with Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
