name: Reviewdog Linting

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-setup@v1
      - run: reviewdog -version
