name: prod workflow
on:
 workflow_dispatch:
 push:
    branches:
        - master
jobs:
    prod_build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with: 
                node-version: 20
            - name: checking out code
              uses: actions/checkout@master
            - name: Build project
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with: 
                name: build-artifact
                path: dist  
              